### PR TITLE
Drum Kit Website added

### PR DESCRIPTION
**Pull request by Anupam1603**
No c++/c flies are there in the project;
i have star the repo
Started following you ;
there s a snapshot of the website for your reference  in the folder as well and im attaching here also;
Website snap

### CODE REVIEW

**Comment by invad3r07** [comment]
You really started following him?

**Comment by invad3r07** [comment]
Nevermind

**Comment by Anupam1603** [comment]
Hey I followed the rules but still it's showing not accepted ?

**Comment by Anupam1603** [comment]
Hey there , my submission is getting counted as not accepted on hactober site !!

**Comment by Anupam1603** [comment]
Hey there my pr is not getting count for hacktober , what's the problem?

**Pull request merged**
