### PR TITLE
timer

### PR DESCRIPTION
**Pull request by sidhrth04**
@shubham7668, Please merge this pr with hacktober badge 
it will be a very good help 
thank you.

### CODE REVIEW

**Comment by invad3r07** [comment]
Rules:-
1)Follow him and add star in this repository
2)No c++/c file will be accepted

Follow all rules you will get hacktoberfest-accepted tag

**Comment by sidhrth04** [comment]
followng both the rules @invad3r07

**Review by invad3r07 — CHANGES_REQUESTED** [review]
Add snapshots of working project

**Comment by invad3r07** [comment]
image

@shubham7668

**Comment by sidhrth04** [comment]
image

**Pull request merged**
