### PR TITLE
Merge this Registration Form built using html and css

### PR DESCRIPTION
**Pull request by aryangupta899**
Kindly merge this project for hacktoberfest

### CODE REVIEW

**Comment by shubham7668** [comment]
Rules:-
1)Follow @shubham7668 and add star in this repository
2)No c++/c file will be accepted
3)Add snapshots of working project

Follow all rules in order to get hacktoberfest-accepted tag

**Comment by shubham7668** [comment]
image

Is this really yours?
Send us deployed link

**Comment by aryangupta899** [comment]
> image
> 
> Is this really yours? Send us deployed link

Hi yes, I built this for my college's (NSIT) robotic society as a part of the audition to join the society.
Unfortunately I wasn't shortlisted/selected into the society.
But I built this project on the guidelines provided by the college society as they wanted to see whether the applying candidates knew basic webdev or not.
So yes, this is 100% my own project. I put in the email id because the college societies guidelines wanted us to put the email.
So kindly remove the invalid label.

**Comment by shubham7668** [comment]
Snapshots or deployed link?

**Comment by shubham7668** [comment]
Make sure to Follow @shubham7668 and add star in this repository

**Comment by aryangupta899** [comment]
> Snapshots or deployed link?
PFA the snapshots:
Capture1
Capture2
Capture3

**Pull request merged**
