### PR TITLE
Update A Memory_Game

### PR DESCRIPTION
**Pull request by Sanyam-7**
Merge Memory_Game(Using HTML , CSS , JavaScript).
Please ADD A HacktoberFest Label #HacktoberFest_2022.

### CODE REVIEW

**Comment by invad3r07** [comment]
Rules:-
1)Follow @shubham7668 and add star in this repository
2)No c++/c file will be accepted
3)Add snapshots of working project

Follow all rules in order to get hacktoberfest-accepted tag

**Comment by Sanyam-7** [comment]
Where we add snapshot of our working project

**Comment by Sanyam-7** [comment]
Uploading VID_20221004_192122145.mp4…

**Comment by Sanyam-7** [comment]
I completed all the rule , why my contribution in the review section

**Pull request merged**
