### PR TITLE
Gallery app

### PR DESCRIPTION
**Pull request by KryptonANSHU**
This is a Simple Web based Gallery App which has cool Animations while seeing the photo.

I am attaching the Video related to it. I hope it will be helpful

https://user-images.githubusercontent.com/72062616/193439485-f1e9cbed-e98d-4985-a6ee-3f104c629b99.mp4

### CODE REVIEW

**Comment by invad3r07** [comment]
image

Looks fine to me

**Review by shubham7668 — APPROVED** [review]

**Comment by invad3r07** [comment]
Hey @KryptonANSHU 
we are looking for 2 tammates for hacksquad event 
Would you participate with us

More info about about hacksquad -> https://www.hacksquad.dev/#events

**Comment by invad3r07** [comment]
Invite link if you want to 
https://www.hacksquad.dev/invite/cl8rrojbx065709mtmeqr1xam

**Comment by KryptonANSHU** [comment]
> Hey @KryptonANSHU we are looking for 2 teammates for hacksquad event Would you participate with us
> 
> More info about about hacksquad -> https://www.hacksquad.dev/#events

Hey @invad3r07 , Thnx for the Invitation but I already have participated in hacksquad with my team. 😅

**Comment by invad3r07** [comment]
> > Hey @KryptonANSHU we are looking for 2 teammates for hacksquad event Would you participate with us
> > More info about about hacksquad -> https://www.hacksquad.dev/#events
> 
> Hey @invad3r07 , Thnx for the Invitation but I already have participated in hacksquad with my team. 😅

ohh! nevermind 
All the best 🚀

**Pull request merged**
