### PR TITLE
react project dshboard for classroom manager

### PR DESCRIPTION
**Pull request by ayushkedia05**

### CODE REVIEW

**Review by shubham7668 — CHANGES_REQUESTED** [review]
Rules:-
1)Follow me and add star in this repository
2)No c++/c file will be accepted

Follow all rules you will get hacktoberfest-accepted tag

**Comment by ayushkedia05** [comment]
cpp removed and starres

**Comment by invad3r07** [comment]
Merging
Make sure to follow him as well @ayushkedia05 
Ping after follow i will five hactktoberfest-accepted tag

**Comment by ayushkedia05** [comment]
done

**Comment by ayushkedia05** [comment]
please give hacktober tag

**Pull request merged**
